In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,6,32,7]],np.int8)

In [3]:
myarr[0,1]

np.int8(6)

## ** Array creation : **

In [4]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarray.dtype

dtype('int64')

In [8]:
listarray.size

9

In [9]:
listarray.shape

(3, 3)

In [10]:
np.array({34,67,45})

array({34, 67, 45}, dtype=object)

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [17]:
np.empty((4,6))

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        6.23058707e-307, 8.90105597e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60220528e-306, 7.56602523e-307,
        1.42417221e-306, 1.37961641e-306, 2.22522597e-306],
       [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 1.60220800e-306,
        7.56589622e-307, 1.11260144e-306, 8.34449806e-308]])

In [18]:
np.empty_like(myarr)

array([[0, 0, 0, 0]], dtype=int8)

In [19]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
arr=np.arange(99)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [24]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr.shape


(99,)

In [29]:
x = ([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
ar = np.array(x)

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ar.sum(axis=0)

array([12, 15, 18])

In [34]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [36]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
ar.flat

In [38]:
 for item in ar.flat:
     print(item)

1
2
3
4
5
6
7
8
9


In [52]:
ar.ndim

2

In [41]:
ar.nbytes

72

In [42]:
one = np.array([1,3,5,76,98])

In [50]:
one.argmax()

np.int64(4)

In [51]:
ar.argmin()

np.int64(0)

In [49]:
one.argsort()

array([0, 1, 2, 3, 4])

In [54]:
ar.argmin()

np.int64(0)

In [55]:
ar.argmax()

np.int64(8)

In [57]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [58]:
ar.argmax(axis=0)

array([2, 2, 2])

In [60]:
ar.argmax(axis=1)

array([2, 2, 2])

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [63]:
ar2=([[1,3,5],[3,6,8],[3,4,5]])

In [64]:
ar+ar2

array([[ 2,  5,  8],
       [ 7, 11, 14],
       [10, 12, 14]])

In [65]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.where(ar>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [68]:
np.count_nonzero(ar)

np.int64(9)

In [70]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [71]:
import sys

In [72]:
py_ar=[0,3,6,2]

In [73]:
np_ar=np.array(py_ar)

In [75]:
sys.getsizeof(1)*len(py_ar)

112

In [78]:
np_ar.itemsize*np_ar.size

32

In [80]:
np_ar.tolist()

[0, 3, 6, 2]